
version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/decentralized-db
      - INFURA_PROJECT_ID=your_infura_project_id
      - JWT_SECRET=your_jwt_secret

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
